/**
 * types/database.types.ts
 *
 * Supabase database type scaffold.
 *
 * In production this file is GENERATED by the Supabase CLI:
 *   npx supabase gen types typescript --local > types/database.types.ts
 *
 * The hand-written scaffold below matches the shape that `supabase gen types`
 * produces. Once you run migrations and generate the real types, delete the
 * hand-written sections and replace with the generated output.
 *
 * Usage:
 *   import type { Database } from "@/types/database.types";
 *   import type { Tables } from "@/types/database.types";
 *
 *   // Shorthand for a single table's row type:
 *   type ProductRow = Tables<"products">;
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * The top-level Database type that the Supabase client is parameterized with:
 *   createClient<Database>(url, key)
 *
 * TODO: Replace this entire type with the output of:
 *   npx supabase gen types typescript --local > types/database.types.ts
 */
export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// ---------------------------------------------------------------------------
// Convenience helpers — mirrors the Supabase generated type helpers
// ---------------------------------------------------------------------------

/** Shorthand for a table's full Row type. */
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

/** Shorthand for a table's Insert type. */
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

/** Shorthand for a table's Update type. */
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

/** Shorthand for a database enum. */
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
